services:
  high-load:
    build:
      context: .
      dockerfile: Dockerfile-console
    container_name: highload-console
    image: highload:console
    environment:
      - MADE_UP_VARIABLE=SomeValue
    # expose:
    #   - 3306