name: HighLoad Test
author: Udo Nesshoever
version: 1
description: Test green measurement with personalized software

# We need an explicit networks part, as we do not auto-generate networks for containers
networks:
  highload-network:

services:
  highload-api-cont:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: highload:api
    ports:
      - "80:80"

flow:
  - name: Small-Stress
    container: highload-api-cont
    commands:
      - type: console
        command: curl -X 'POST' 'http://localhost/init?itemCount=200&taskCount=10' -H 'accept:text/plain' -d ''
        shell: bash
        note: Starting a little stress
        log-stderr: True
        log-stdout: True