# We need an explicit networks part, as we do not auto-generate networks for containers
networks:
  highload-network:

services:
  # There is no container_name directive. All services keys act directly as container names
  highload-container:
    # If you build your file with docker compose in the example above this image name should be the one you have now locally
    image: highload-image
    container_name: highload
    environment:
      - MADE_UP_VARIABLE=SomeValue
    # networks must be explicitly stated in each service
    networks:
      - highload-network

flow:
  - name: Small-Stress
    container: highload-container
    commands:
      - type: console
        command: HighLoad.Console 80 6
        note: Starting a little stress